### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by valgur** [sentinelsat/sentinelsat#391]
Although the [zerover](https://0ver.org/) versioning scheme has served us well, I think we are feature-complete enough that it's due time for a proper 1.0 release, especially with the recent additions.
All of the improvement suggestions from an older discussion on this (#108) have now been implemented.

Obviously, all of the outstanding PRs should be merged first, but I would also like to incorporate some other smallish changes/additions:

- [x] 1. I would change the CLI query param format from `-q x=y,z=w` to `-q x=y -q z=w`, which is a bit more flexible, I think.
- [x] 2. Interpret repeated CLI query keywords as a set of allowed values, so for example `-q relativeorbitnumber=105 -q relativeorbitnumber=220` would get translated to `(relativeorbitnumber:105 OR relativeorbitnumber:220)`. This would also apply to `--name` and `--uuid`. (Might as well deprecate them at this point, since they can be replaced by `-q identifier=...` and `-q uuid=...`.) 
- [x] 3. I think the default date range values can cause a lot of confusion, especially if trying to download a specific product with `--name` or `--uuid`. Possible solutions would be to drop the default date range values entirely or to not set it for `--start` and make it a required param. The first one is neater and we kind of provide a warning about excessively large queries by showing a progress bar in such cases. Related: #456
- [x] 4. ~~I would like to add Python API functionality to make downloading individual files from products more convenient. These could be something like `api.list_product_files(uuid, path)`, `api.get_product_file_url(uuid, path)` and `api.download_product_file(uuid, path)`. The list function should probably also include some metadata like file sizes.~~ Actually this can be added after v1.0 release also. Moved to ~~#392~~ #291.
- [x] 5. Should update the readme with the first "getting started" making use of the nice and user friendly `--location` feature instead of `--geometry`.
- [x] 6. Have `--footprints` take output file path. Support for `-` for stdout would also be nice (#153).
- [ ] 7. Convert GeoJSON input into `GEOMETRYCOLLECTION` WKT for multi-feature input. (#114)

Will also have to take another look at the issues collected under the [v1.0 milestone](https://github.com/sentinelsat/sentinelsat/milestone/1) and the milestones of all others.

What do you think? I can probably take care of implementing these suggestions next week, if you agree with them.

**Comment by valgur** [comment]
I updated the milestones for all open issues. Feel free to have a look and adjust them, if necessary. https://github.com/sentinelsat/sentinelsat/milestones

**Comment by j08lue** [comment]
Very good list! I agree with all points and proposed CLI changes. 

Regarding the date CLI parameter, I also think that removing the defaults would be fine. I remember that our rationale was that people should not easily by accident hit the DHuS with a huge query. But I think we do not have to take that responsibility.

We have also been wanting to split up the monolithic `sentinel` module and the `SentinelAPI` class, which would change the internal code structure quite a bit. It sounds like a big task, but perhaps it is not. When all the features are implemented, I could make a PR for a break-up that preserves the public API.

**Comment by Fernerkundung** [comment]
All of those sound lAll of those sound like good changes to implement to hit the 1.0 milestone :+1: 

Thanks for typing up that list and bringing up that discussion. I've had the feeling that we are mostly feature complete since v0.13 - hence the long cycle between releases.

Let's add the proposed polished and UX changes and push `sentinelsat` over to v1.0 :rocket:

**Comment by Fernerkundung** [comment]
For points 1 to 3: Should we create issues for them or do you plan to hammer these out as straight PRs?

asking because of this line
> I can probably take care of implementing these suggestions

**Comment by j08lue** [comment]
I saw some discussion on all the open source projects that seem to be eternally stuck in `0.m.b`. The takeaway point was: Face it, people are using this for production. So make it v1 now without further considerations.

With all the great work you put into the code and repo setup in the past few days, @valgur, I think this would be a perfect time to take that step. What do you think, @Fernerkundung?

**Comment by valgur** [comment]
I definitely agree.

**Comment by j08lue** [comment]
Great! So will the `0.15.0` release (with the features discussed there) become our `1.0.0` instead?

**Comment by valgur** [comment]
:tada: As far as I'm concerned, the breaking changes I wanted to include in v1.0 have been merged. The idea nr 7 is an incremental change and can be left for a later release.

Thanks, @j08lue, for the prompt reviews! Much appreciated.

Closing this one to continue the discussion in #434.
