### ISSUE TITLE
Make proper release for v1.0

### ISSUE THREAD

**Issue by j08lue** [sentinelsat/sentinelsat#434]
Needs

- [x] Update package version at https://github.com/sentinelsat/sentinelsat/blob/main/sentinelsat/__init__.py#L1
- [x] Update link to latest changes on main under https://github.com/sentinelsat/sentinelsat#changelog
- [x] Update changelog with release
- [x] Update AUTHORS.rst
- [x] Copy relevant part of changelog into the release description
- [x] Publish artifacts
- [x] Make sure docs are built and updated
- [x] Start a new dev version section in changelog

**Comment by valgur** [comment]
Critical open issues / PRs I think should be included in v0.15, all of them pretty small:

- [ ] #421 Use HEAD request for LTA triggers
- [ ] #455  -d no longer downloads; prints debug messages 
- [ ] #456 --uuid restricts search time range to yesterday - today
- [ ] #448 Gracefully handle cancelled futures

**Comment by avalentino** [comment]
It would be nice to have in the next release also the support for orbit files (see #436 and #441), at least as a provisional API.
Please note that it is under discussion the possibility to to add a sentinelsat based backend to sentineleof (see https://github.com/scottstanie/sentineleof/issues/6).

The implementation is very basic but complete.

I would like to add some unit test but, unfortunately, the SciHub GNSS end-point seems to be broken at the moment (see also the discussion in https://github.com/johntruckenbrodt/pyroSAR/issues/141) so making tests is currently very hard.

**Comment by j08lue** [comment]
No need to rush this. We can make releases as often as we like and adding the GNSS functionality would warrant another release soon. Let us rather spend the time needed to get everything right - but not wait with releasing the features that already are in that state.

**Comment by valgur** [comment]
So, let's make the next release v1.0. I assume you agree @j08lue and @Fernerkundung?

**Comment by Fernerkundung** [comment]
Agreed - let's make the next release a 1.0. We have a few open issues that are tracked with the 1.0 milestone but those could also be pushed to 1.1. https://github.com/sentinelsat/sentinelsat/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0

Just the time we had between the releases with no major breaks is a good indication that the project matured past the 1.0 threshold.

**Comment by j08lue** [comment]
> those could also be pushed to 1.1

💯

**Comment by valgur** [comment]
After merging #482 everything looks ready to go for v1.0.0. I can take care of creating the release tomorrow.

**Comment by j08lue** [comment]
Wow, you have been on 🔥 , @valgur! Great work with all the fixes, improvement, and cleanup. 🚀 All clear for v1.

**Comment by valgur** [comment]
And it's up. v1.0.0 has been released.

Thanks to everyone who contributed to this release – @avalentino, @gbaier, @thomasyoung-audet, @mackland, @fwfichtner, @dwlsalmeida, @lucadelu! It was a long changelog.
